### ISSUE TITLE
Some BUGs for rosmake lsd_slam  

### ISSUE THREAD

**Issue by heimagithub** [jim1993/Ardrone_indoor_slam#2]
Hi jim 

I would ask how to publish pointcloud for gloabal map?

I look your FinalProject..  But it only say replace two files (keyframeDisplay.cpp and keyframeDisplay.h) But when I run rosmake. some bug like 

lsd_slam_viewer::keyframeMsg_<std::allocator<void> >’ has no member named ‘scale’
    scale_para = msg->scale;

I replace keyframe.msg but more bugs come out

code in line 247 of keyframeDisplay.cpp
cloud.points[total-1].x = scale * pt[0] * scale_para;
cloud.points[total-1].y = scale * pt[1] * scale_para;
cloud.points[total-1].z = scale * pt[2] * scale_para;

"scale" is undeclare ?? 

Is something wrong?  Please help me. thank you.

**Comment by heimagithub** [comment]
I delete the msg_gen in lsd_slam_viewer and run rosmake again. It's OK.

**Comment by haochihlin** [comment]
Hi
Sorry for the late reply.
And it is good to hear that you solve the issue!
