### ISSUE TITLE
Basic operation help want

### ISSUE THREAD

**Issue by yin1008** [jim1993/Ardrone_indoor_slam#3]
Hi, Jim. Thanks your great work!  I am new in slam and I would like to repeat your work. Could you please give me some instructions on how to quick start? Thanks a lot in advance.

By the way, how to open Final Project-Jim.baskets file?

Kind regards,

2018.1.11
Yin

**Comment by haochihlin** [comment]
Hi @yin1008 

It is glad to hear you that you are interested in this project.
To begin with, I would suggest you to read the notes in "Final Project-Jim.baskets".
You can download related ubuntu app to open it:
https://apps.ubuntu.com/cat/applications/lucid/basket/

Cheers,
HaoChih, Lin

**Comment by yin1008** [comment]
Hi, Lin! Thanks for your kind remind and I made the practice as told in baskets files. But errors  always occurred as below when I compiled the LSD-SLAM.:
[rosbuild] Found SSE3 extensions, using flags: -msse3 -mfpmath=sse
  -- Configuring incomplete, errors occurred!
[rosmake-1] Finished <<< lsd_slam_viewer [FAIL] [ 2.71 seconds ]                
[ rosmake ] Halting due to failure in package lsd_slam_viewer. 

Could you please give me some sulution?  Thanks again!

Kind regards,
Yin
