### ISSUE TITLE
lsd_slam  tracking lost

### ISSUE THREAD

**Issue by axelfar** [jim1993/Ardrone_indoor_slam#4]
Hello Jim,
Thanks for this project! 
I try to use your code on a AR.Drone 2.0 and all seem works. But when I use lsd_slam I lose immediately the tracking. 
To do that I use your launcher "ardrone_navigation". 
I forgot something?

Best regards,
Axel

EDIT: The tracking works when I use the command :
 _rosrun lsd_slam_core live_slam /image:=/ardrone/front/image_raw _calib:={path to my calibration file}

I create the calibration file with "camera_calibration.exe" from opencv. I try with your calibration files but for me lsd_slam doesn't work because the last parameter is not 0.

**Comment by haochihlin** [comment]
Hi @axelfar 
Thank you for being interested in this pkgs.
However, this repo was no longer maintained!
The updated and supported version now is handled by HyphaROS:
https://github.com/Hypha-ROS/hypharos_ardrone_navigation
(There is step by step tutorial on the new repo! )

If you have any problem, could you please open an issue in there.

Cheers,
HaoChih, Lin
